/**
 * Formatting utilities for output
 */

import type { Summary } from '../core/types.js';

/**
 * Format summary as markdown
 */
export function formatSummaryAsMarkdown(summary: Summary): string {
  const lines: string[] = [];

  lines.push(`# ${summary.title}`);
  lines.push('');

  if (summary.bullets.length > 0) {
    lines.push('## Key Findings');
    for (const bullet of summary.bullets) {
      lines.push(`- ${bullet}`);
    }
    lines.push('');
  }

  if (summary.errorGroups.length > 0) {
    lines.push('## Error Groups');
    for (const error of summary.errorGroups) {
      lines.push(`- **${error.description}** (${error.count} occurrences)`);
      if (error.firstOccurrence) {
        lines.push(`  - First occurrence: ${error.firstOccurrence}`);
      }
      if (error.rootCauseAnalysis) {
        lines.push(`  - **Root Cause Analysis**: ${error.rootCauseAnalysis}`);
      }
      if (error.investigationGuidance) {
        lines.push(`  - **Investigation Guidance**: ${error.investigationGuidance}`);
      }
      if (error.likelyCause && !error.rootCauseAnalysis) {
        // Only show likelyCause if rootCauseAnalysis is not provided (backward compatibility)
        lines.push(`  - Likely cause: ${error.likelyCause}`);
      }
    }
    lines.push('');
  }

  if (summary.performanceHotspots.length > 0) {
    lines.push('## Performance Hotspots');
    for (const hotspot of summary.performanceHotspots) {
      const severity = hotspot.severity === 'high' ? '🔴' : hotspot.severity === 'medium' ? '🟡' : '🟢';
      lines.push(`- ${severity} **${hotspot.operation}**: ${hotspot.issue}`);
      if (hotspot.rootCauseAnalysis) {
        lines.push(`  - **Root Cause Analysis**: ${hotspot.rootCauseAnalysis}`);
      }
      if (hotspot.investigationGuidance) {
        lines.push(`  - **Investigation Guidance**: ${hotspot.investigationGuidance}`);
      }
    }
    lines.push('');
  }

  if (summary.suggestedActions.length > 0) {
    lines.push('## Suggested Actions');
    for (let i = 0; i < summary.suggestedActions.length; i++) {
      lines.push(`${i + 1}. ${summary.suggestedActions[i]}`);
    }
    lines.push('');
  }

  lines.push(`_Generated by ${summary.metadata.model} (${summary.metadata.tokensUsed} tokens)_`);

  return lines.join('\n');
}

/**
 * Format summary as plain text (no markdown)
 */
export function formatSummaryAsPlainText(summary: Summary): string {
  const lines: string[] = [];

  lines.push(summary.title);
  lines.push('');

  if (summary.bullets.length > 0) {
    lines.push('Key Findings:');
    for (const bullet of summary.bullets) {
      lines.push(`  - ${bullet}`);
    }
    lines.push('');
  }

  if (summary.errorGroups.length > 0) {
    lines.push('Error Groups:');
    for (const error of summary.errorGroups) {
      lines.push(`  - ${error.description} (${error.count} occurrences)`);
      if (error.firstOccurrence) {
        lines.push(`    First occurrence: ${error.firstOccurrence}`);
      }
      if (error.rootCauseAnalysis) {
        lines.push(`    Root Cause Analysis: ${error.rootCauseAnalysis}`);
      }
      if (error.investigationGuidance) {
        lines.push(`    Investigation Guidance: ${error.investigationGuidance}`);
      }
      if (error.likelyCause && !error.rootCauseAnalysis) {
        lines.push(`    Likely cause: ${error.likelyCause}`);
      }
    }
    lines.push('');
  }

  if (summary.performanceHotspots.length > 0) {
    lines.push('Performance Hotspots:');
    for (const hotspot of summary.performanceHotspots) {
      lines.push(`  - [${hotspot.severity.toUpperCase()}] ${hotspot.operation}: ${hotspot.issue}`);
      if (hotspot.rootCauseAnalysis) {
        lines.push(`    Root Cause Analysis: ${hotspot.rootCauseAnalysis}`);
      }
      if (hotspot.investigationGuidance) {
        lines.push(`    Investigation Guidance: ${hotspot.investigationGuidance}`);
      }
    }
    lines.push('');
  }

  if (summary.suggestedActions.length > 0) {
    lines.push('Suggested Actions:');
    for (let i = 0; i < summary.suggestedActions.length; i++) {
      lines.push(`  ${i + 1}. ${summary.suggestedActions[i]}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Format summary for Slack (markdown with Slack-specific formatting)
 * Slack has a 4000 character limit per message, so we truncate if needed
 */
export function formatSummaryForSlack(summary: Summary): string {
  const SLACK_MAX_LENGTH = 4000;
  const TRUNCATE_BUFFER = 200; // Leave room for truncation message
  
  const lines: string[] = [];

  lines.push(`*${summary.title}*`);
  lines.push('');

  if (summary.bullets.length > 0) {
    lines.push('*Key Findings:*');
    for (const bullet of summary.bullets) {
      lines.push(`• ${bullet}`);
    }
    lines.push('');
  }

  if (summary.errorGroups.length > 0) {
    lines.push('*Error Groups:*');
    for (const error of summary.errorGroups) {
      lines.push(`• *${error.description}* (${error.count} occurrences)`);
      if (error.firstOccurrence) {
        lines.push(`  _First: ${error.firstOccurrence}_`);
      }
      // Truncate RCA and guidance to be more concise for Slack
      if (error.rootCauseAnalysis) {
        const rca = error.rootCauseAnalysis.length > 150 
          ? error.rootCauseAnalysis.substring(0, 147) + '...' 
          : error.rootCauseAnalysis;
        lines.push(`  *RCA:* ${rca}`);
      }
      if (error.investigationGuidance) {
        const guidance = error.investigationGuidance.length > 150 
          ? error.investigationGuidance.substring(0, 147) + '...' 
          : error.investigationGuidance;
        lines.push(`  *Check:* ${guidance}`);
      }
      if (error.likelyCause && !error.rootCauseAnalysis) {
        lines.push(`  _Cause: ${error.likelyCause}_`);
      }
    }
    lines.push('');
  }

  if (summary.performanceHotspots.length > 0) {
    lines.push('*Performance Hotspots:*');
    for (const hotspot of summary.performanceHotspots) {
      const severity = hotspot.severity === 'high' ? '🔴' : hotspot.severity === 'medium' ? '🟡' : '🟢';
      lines.push(`• ${severity} *${hotspot.operation}*: ${hotspot.issue}`);
      if (hotspot.rootCauseAnalysis) {
        const rca = hotspot.rootCauseAnalysis.length > 150 
          ? hotspot.rootCauseAnalysis.substring(0, 147) + '...' 
          : hotspot.rootCauseAnalysis;
        lines.push(`  *RCA:* ${rca}`);
      }
      if (hotspot.investigationGuidance) {
        const guidance = hotspot.investigationGuidance.length > 150 
          ? hotspot.investigationGuidance.substring(0, 147) + '...' 
          : hotspot.investigationGuidance;
        lines.push(`  *Check:* ${guidance}`);
      }
    }
    lines.push('');
  }

  if (summary.suggestedActions.length > 0) {
    lines.push('*Suggested Actions:*');
    for (let i = 0; i < summary.suggestedActions.length; i++) {
      lines.push(`${i + 1}. ${summary.suggestedActions[i]}`);
    }
    lines.push('');
  }

  let message = lines.join('\n');
  
  // Truncate if message is too long
  if (message.length > SLACK_MAX_LENGTH) {
    const truncateAt = SLACK_MAX_LENGTH - TRUNCATE_BUFFER;
    // Try to truncate at a line boundary
    const truncated = message.substring(0, truncateAt);
    const lastNewline = truncated.lastIndexOf('\n');
    const finalMessage = lastNewline > 0 
      ? truncated.substring(0, lastNewline)
      : truncated;
    
    message = finalMessage + '\n\n_... [Message truncated due to length. See full details in logs.]_';
  }

  return message;
}
